# Generated by Django 4.2.28 on 2026-02-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={
                "ordering": ["-github_updated_at"],
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
            },
        ),
        migrations.AddField(
            model_name="repository",
            name="default_branch",
            field=models.CharField(default="main", max_length=100),
        ),
        migrations.AddField(
            model_name="repository",
            name="github_pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_issues",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_projects",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_wiki",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="watchers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("delivery_id", models.CharField(max_length=100, unique=True)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_webhook_id", models.CharField(max_length=100)),
                ("webhook_url", models.URLField(max_length=500)),
                ("secret", models.CharField(max_length=100)),
                ("events", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("total_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "repository_webhooks",
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("message", models.TextField()),
                ("html_url", models.URLField(max_length=500)),
                ("author_name", models.CharField(max_length=255)),
                ("author_email", models.CharField(max_length=255)),
                (
                    "author_login",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "author_avatar_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("total_changes", models.IntegerField(default=0)),
                ("committed_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "commits",
                "ordering": ["-committed_at"],
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField(blank=True, null=True)),
                ("state", models.CharField(max_length=20)),
                ("html_url", models.URLField(max_length=500)),
                ("author_login", models.CharField(max_length=100)),
                (
                    "author_avatar_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("head_branch", models.CharField(max_length=255)),
                ("base_branch", models.CharField(max_length=255)),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("changed_files", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("review_comments_count", models.IntegerField(default=0)),
                ("commits_count", models.IntegerField(default=0)),
                ("mergeable", models.BooleanField(blank=True, null=True)),
                ("merged", models.BooleanField(default=False)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "pull_requests",
                "ordering": ["-created_at"],
                "unique_together": {("repository", "number")},
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField(blank=True, null=True)),
                ("state", models.CharField(max_length=20)),
                ("html_url", models.URLField(max_length=500)),
                ("author_login", models.CharField(max_length=100)),
                (
                    "author_avatar_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("labels", models.JSONField(blank=True, default=list)),
                ("assignees", models.JSONField(blank=True, default=list)),
                ("comments_count", models.IntegerField(default=0)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "issues",
                "ordering": ["-created_at"],
                "unique_together": {("repository", "number")},
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_login", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("html_url", models.URLField(max_length=500)),
                ("contributions", models.IntegerField(default=0)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "contributors",
                "ordering": ["-contributions"],
                "unique_together": {("repository", "github_login")},
            },
        ),
    ]
