# Generated by Django 4.2.28 on 2026-02-21 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_conversation_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PRAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("issues_found", models.IntegerField(default=0)),
                ("security_score", models.IntegerField(default=100)),
                ("performance_score", models.IntegerField(default=100)),
                ("quality_score", models.IntegerField(default=100)),
                ("complexity_score", models.IntegerField(default=0)),
                ("security_issues", models.JSONField(default=list)),
                ("performance_issues", models.JSONField(default=list)),
                ("code_smells", models.JSONField(default=list)),
                ("positive_points", models.JSONField(default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_time", models.FloatField(default=0.0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("comment_posted", models.BooleanField(default=False)),
                (
                    "github_comment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pull_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "PR Analysis",
                "verbose_name_plural": "PR Analyses",
                "db_table": "pr_analyses",
            },
        ),
        migrations.CreateModel(
            name="DocumentationGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("readme", "README"),
                            ("api", "API Documentation"),
                            ("contributing", "Contributing Guide"),
                            ("changelog", "Changelog"),
                            ("full", "Full Documentation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("content", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("generation_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentation_generations",
                        to="core.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documentation_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommitAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("total_commits", models.IntegerField(default=0)),
                ("good_commits", models.IntegerField(default=0)),
                ("needs_improvement", models.IntegerField(default=0)),
                ("quality_score", models.IntegerField(default=0)),
                ("issues", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("best_commits", models.JSONField(default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_analyses",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "commit_analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("alert", "Alert"),
                            ("suggestion", "Suggestion"),
                            ("win", "Win"),
                            ("trend", "Trend"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=50)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.issue",
                    ),
                ),
                (
                    "related_pr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pullrequest",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "code_insights",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
